### ISSUE TITLE
V3 Prototype - Low power mode is broken

### ISSUE THREAD

**Issue by YDrip** [YDrip/ydrip-pcb#2]
Duty cycling the magnetic sensor produces a distorted amplified waveform.

Potential solution: Duty cycle the SLG88103V amplifier. It's possible the opamp feedback network is biasing the sensor and distorting the signal if the amp is always on. Power the mag sensor then the amplifier may allow the signal to settle before amplification.     

Rework required: Connect pin 19 of SLG47004V to pin 1 of the SLG88103V.

**Comment by ScalpRadar** [comment]
Fixed in [24e5011](https://github.com/YDrip/ydrip-pcb/commit/24e5011a16618b0e36a29c7a35e67e57f00b404a). Added opamp power down control to programmable logic.

**Comment by YDrip** [comment]
Fixed in 24e5011. Added opamp power down control to programmable logic.
